title: Alister Munday
description: Working notes and findings.
url: https://alistermunday.com
theme: minima
markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
